baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

# Theme Settings
theme = "tale"
[params]
  Author = "Aaron Katz" # Add the name of the author (this theme only supports one author)
[author]
  name = "Caliburn Security" # Used by the foot copyright